### ISSUE TITLE
NoSuchKey

### ISSUE THREAD

**Issue by rabby0101** [mihakralj/obsidian-cloudsync#1]
<img width="862" alt="Screenshot 2024-12-09 at 19 15 38" src="https://github.com/user-attachments/assets/9a577cd8-91d9-441c-a2e3-093a5d2b1de9">

First I installed and setup one vault, everything was alright. then I installed and setup second vault, after that, this error message is showing. the file name "2024-12-02.md " was on my vault when i was setting up the plugin, later I've deleted that.

**Comment by mihakralj** [comment]
can you turn logging to full debug (in CloudSync settings on top of the window), clear the log and re-run the sync - and then show the detailed debug log. I want to see what a problem is with keys passed to AWS API. Currently it looks like your key is missing (or invalid).

Also update/refresh the plugin to 1.0.9
